//Operators
var a = 5;
var b = a + 2;
console.log(b);
var num1 = 10;
var num2 = 20;
var result = num1 + num2;
console.log(result);
var num3 = 40;
var num4 = 50;
var result2 = num3 - num4;
console.log(result2);
var num5 = 0;
console.log(num5++);
console.log(num5);
console.log(++num5);
var num6 = 5;
var num7 = 4;
console.log(num6 == num7);
console.log(num6 != num7);
var num8 = 5;
var num9 = 2;
console.log(num8 == num9);
console.log(num8 != num9);
console.log(5 < 2);
console.log(5 > 2);
console.log(5 > 2);
console.log(num8++);
console.log(num8);
console.log(++num9);
console.log(++num9);
var num10 = 9;
var num11 = 8;
console.log(num10 != num11);
console.log(num10 == num11);
console.log(num11++);
console.log(++num10);
var c = 5;
var d = 2;
var e;
e = ++c + c++ + --d + d-- + c + d++ + d;
console.log(e);
var f = 0;
var g = 5;
var h;
h = f++ + f++ + ++g + f++ + f-- + ++g;
console.log(h);
var aa = 2;
var bb = 4;
var cc = 5;
var dd = 8;
var ee = 4;
var ff;
ff = (2 + 4 * 5 - 8 / 4);
console.log(ff);
